# Generated by Django 4.1.4 on 2022-12-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(default='gaurang', max_length=50)),
                ('date', models.DateField(verbose_name='')),
                ('intime', models.TimeField(verbose_name='')),
                ('outtime', models.TimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=15)),
                ('Mname', models.CharField(max_length=15)),
                ('Lname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=50)),
                ('Bankname', models.CharField(max_length=50)),
                ('Bankbranch', models.CharField(max_length=5)),
                ('BankAC', models.CharField(max_length=50)),
                ('IFSCCode', models.CharField(max_length=20)),
                ('EmpSSN', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('EFname', models.CharField(max_length=15)),
                ('EMname', models.CharField(max_length=15)),
                ('ELname', models.CharField(max_length=15)),
                ('Eemail', models.CharField(max_length=15)),
                ('Econtact', models.CharField(max_length=50)),
                ('Eaddress', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jobposting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='gaurang')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('contact', models.IntegerField(verbose_name='')),
                ('comments', models.TextField(verbose_name='')),
                ('time', models.TimeField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
            ],
        ),
    ]
