# Generated by Django 4.1.4 on 2022-12-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_attendance_date_alter_attendance_intime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deadlinedate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='deadlinetime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='task',
            field=models.TextField(default='null'),
        ),
    ]
