# Generated by Django 4.1.4 on 2022-12-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_attendance_deadlinedate_attendance_deadlinetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='deadlinedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='deadlinetime',
            field=models.TimeField(),
        ),
    ]
