# Generated by Django 4.1.4 on 2022-12-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_attendance_date_alter_attendance_deadlinedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
