# Generated by Django 4.1.4 on 2022-12-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_jobposting_date_alter_jobposting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlinedate', models.DateField(null=True)),
                ('deadlinetime', models.TimeField(null=True)),
                ('task', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='deadlinedate',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='deadlinetime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='task',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
