# Generated by Django 4.1.4 on 2022-12-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_bankac_alter_employee_econtact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='minqualification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
