# Generated by Django 4.1.4 on 2022-12-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_jobposting_minqualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='vacany',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
