# Generated by Django 4.1.4 on 2022-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_jobposting_schedule_jobposting_vacany'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpSSN', models.IntegerField()),
                ('sdate', models.DateField(null=True)),
                ('edate', models.DateField(null=True)),
                ('leavetype', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhaar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mothertounge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='subcaste',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
