# Generated by Django 4.1.4 on 2023-01-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_leave_empssn_alter_leave_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Egender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenboard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenpercentage',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twelveboard',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twelvepercentage',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twelveyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='approval',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
