# Generated by Django 4.1.4 on 2023-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employee_egender_employee_degree_employee_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpSSN',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
