# Generated by Django 4.1.4 on 2023-01-08 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_employee_id_alter_employee_empssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
