# Generated by Django 4.1.4 on 2023-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_attendance_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='fk',
        ),
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
