# Generated by Django 4.1.4 on 2023-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_remove_attendance_fk_attendance_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
