# Generated by Django 4.1.4 on 2023-01-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_rename_comment_leave_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employee',
        ),
        migrations.AddField(
            model_name='schedule',
            name='EmpSSN',
            field=models.IntegerField(null=True),
        ),
    ]
