# Generated by Django 4.1.4 on 2023-01-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_remove_schedule_employee_schedule_empssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
    ]
