# Generated by Django 4.1.4 on 2023-01-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_remove_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face',
            field=models.FileField(max_length=256, null=True, upload_to='face/'),
        ),
    ]
